CREATE TABLE package_details (
    pack_code CHAR(8) NOT NULL,
    pack_desc CHAR(50) NOT NULL,
    mrkt_desc_eng VARCHAR(60),
    mrkt_desc_tha VARCHAR(60),
    mrkt_desc_3 VARCHAR(350),
    mrkt_desc_4 VARCHAR(350),
    mrkt_desc_5 VARCHAR(350),
    invc_desc_eng VARCHAR(50),
    invc_desc_thai VARCHAR(50),
    esvc_flag CHAR(1) NOT NULL,
    telp_type CHAR(3),
    subr_type CHAR(1),
    pack_type CHAR(2),
    pack_catg SMALLINT,
    pack_clas CHAR(3),
    pack_pdtp CHAR(3),
    fmly_grup_code CHAR(2),
    offr_id INTEGER,
    srvc_type CHAR(2),
    pack_type_grup CHAR(3),
    artm_code SMALLINT,
    disc_code SMALLINT,
    eis_pkgp CHAR(8),
    effc_date DATE NOT NULL,
    expr_date DATE,
    strt_ofst_unit CHAR(1),
    end_ofst_unit CHAR(1),
    strt_ofst_perd SMALLINT,
    end_ofst_perd SMALLINT,
    strt_date DATE,
    end_date DATE,
    time_to_time CHAR(1) NOT NULL,
    xtnd_bldy CHAR(1) NOT NULL,
    enof_pmtn CHAR(1) NOT NULL,
    pack_vald_mode SMALLINT NOT NULL,
    crlm_amnt DECIMAL(10,2) NOT NULL,
    next_pack_code CHAR(8),
    auth_all_hrdw CHAR(1) NOT NULL,
    auth_all_user CHAR(1) NOT NULL,
    idd_flag CHAR(1) NOT NULL,
    idd_max_cnty INTEGER,
    scnd_sim_flag CHAR(1),
    scnd_sim_numb SMALLINT,
    blnc_mssg CHAR(1),
    allw_mnpi CHAR(1) NOT NULL,
    bloc_mnpo_perd SMALLINT NOT NULL,
    warn_swof_perd SMALLINT,
    xtnd_crlm_amnt DECIMAL(8,2),
    intr_cat_crlm DECIMAL(10,2),
    intr_tot_crlm DECIMAL(10,2),
    intr_dtn_crlm DECIMAL(10,2),
    intr_ain_crlm DECIMAL(10,2),
    intr_tmn_crlm DECIMAL(10,2),
    expr_all_user CHAR(1) NOT NULL,
    cust_pmtn_code SMALLINT,
    pmtn_code CHAR(8),
    maxm_subr_shre SMALLINT,
    allw_comp_only CHAR(1) NOT NULL,
    allw_d4u CHAR(1) NOT NULL,
    allw_perd SMALLINT,
    chck_cntr_flag CHAR(1) NOT NULL,
    allw_dupl CHAR(1) NOT NULL,
    bloc_chng_main CHAR(1),
    allw_cmp_only CHAR(1) NOT NULL,
    ovrl_clas_cnfl CHAR(1) NOT NULL,
    finc_pack_type CHAR(2),
    dcop_prce_flag CHAR(1) NOT NULL,
    remk VARCHAR(255),
    pack_bnft_perd SMALLINT,
    crtd_dttm TIMESTAMP NOT NULL,
    crtd_by CHAR(12) NOT NULL,
    last_chng_dttm TIMESTAMP NOT NULL,
    last_chng_by CHAR(12) NOT NULL
);