curl -X POST  -H "Content-Type:application/json" 
-d 
'{
  "@type": "INDY",
  "individualIdentification": [
    {
      "identificationType": "01",
      "identificationId": "1234567890123",
      "validFor": {
        "endDateTime": "2030-12-31T00:00:00Z"
      }
    }
  ],
  "language": "T",
  "title": "Mr.",
  "givenName": "Somchai",
  "familyName": "Jaidee",
  "maritalStatus": "S",
  "gender": "M",
  "nameType": "INDY",
  "contactLanguage": "THA",
  "nationality": "THA",
  "birthDate": "1990-05-15T00:00:00Z",
  
  "externalReference": [
    {
      "type": "PartyExtBillingID",
      "name": "BIL12345678"
    },
    {
      "type": "PartyExtID",
      "name": "EXT98765432"
    }
  ],
  
  "partyCharacteristic": [
    {
      "name": "occupationCode",
      "value": "502"
    },
    {
      "name": "timeInBusiness",
      "value": "0101"
    },
    {
      "name": "salaryLevel",
      "value": "01"
    },
    {
      "name": "grade",
      "value": "1"
    },
    {
      "name": "largeCustomerIndicator",
      "value": "78"
    },
    {
      "name": "subscriberType",
      "value": "RPI"
    },
    {
      "name": "sourceCustomerType",
      "value": "73"
    },
    {
      "name": "parentTitle",
      "value": "Ms."
    },
    {
      "name": "parentFirstName",
      "value": "Somsri"
    },
    {
      "name": "parentLastName",
      "value": "Jaidee"
    },
    {
      "name": "parentContact",
      "value": "0896543210"
    },
    {
      "name": "parentId",
      "value": "1234567890124"
    },
    {
      "name": "totalNoOfSubscriber",
      "value": "3"
    },
    {
      "name": "maxAllowOnlySubscriber",
      "value": "5"
    },
    {
      "name": "dealPool",
      "value": "STANDARD"
    },
    {
      "name": "loyalty",
      "value": "GOLD"
    }
  ],
  
  "contactMedium": [
    {
      "type": "phoneNumber",
      "preferred": true,
      "phoneNumber": "088888888"
    },
    {
      "type": "address",
      "addressType": "01",
      "street1": "123 Sukhumvit Road",
      "street2": "Apartment 456",
      "postCode": "10110",
      "country": "THA",
      "building": "Sukhumvit Tower",
      "homenumber": "123/456",
      "moo": "5",
      "tumbol": "Khlong",
      "city": "Watthana",
      "accomdationType": "HOME",
      "time_at_addr": "24"
    },
    {
      "type": "address",
      "addressType": "02",
      "street1": "789 Silom Road",
      "postCode": "10500",
      "country": "THA",
      "homenumber": "789",
      "tumbol": "Silom",
      "city": "Bang Rak"
    }
  ]
}'

http://localhost:9999/party/api/partymanagement/V1/individual